### ISSUE TITLE
Allow adding some kind of ownership information to the lockfile

### ISSUE THREAD

**Issue by pedro-stanaka** [sethvargo/go-gcslock#10]
## Summary

In some cases it is interesting to have ownership information about who owns the lock currently. I would like to see an optional flag set to enable this kind of information in the lock metadata. We could use the options created in #8 and build upon that.

**Comment by sethvargo** [comment]
Hi @pedro-stanaka - thank you for opening an issue. The API surface for this library is intentionally small, and I'm not interested in expanding it. You might consider forking this library and adding the functionality that you need instead. Thanks!
