### ISSUE TITLE
Use github.com/fullstorydev/emulators for "integration" test

### ISSUE THREAD

**Issue by pedro-stanaka** [sethvargo/go-gcslock#9]
## Summary

The integration test assume a real connection with Google Cloud Platform and just assumes a env var is set (`TEST_BUCKET`) to actually trying to run the test, which could be dangerous in case it is set by accident to something being used in the real world.

The repo could use the really good emulator github.com/fullstorydev/emulators for GCS and avoid running real tests with live connections.

**Comment by sethvargo** [comment]
Hi @pedro-stanaka - thank you for opening an issue. It's important to test against a real environment, since emulators will not catch eventual consistency issues like the real implementation.
